# file: vim/tasks/main.yml

- name: Vim | Make sure vim-tiny is uninstalled
  apt:
    pkg: vim-tiny
    state: absent

- name: Vim | Make sure your favourite vim flavour is installed
  apt:
    pkg: "{{vim_base}}"
    state: present

- name: Vim | Install additional vim packages
  apt:
    pkg: "{{item}}"
    state: present
  with_items: vim_extras
  when: vim_extras|length > 0
